#pragma once

#include "core_server/internal/parsing/option_declaration/autogenerated/OptionDeclarationParserBaseVisitor.h"

namespace CORE::Internal::Parsing::Option {
class QuarantineOptionVisitor : public OptionDeclarationParserBaseVisitor {
 public:
  virtual std::any
  visitQuarantine_policy(OptionDeclarationParser::Quarantine_policyContext* ctx) override {
  }
};
}  // namespace CORE::Internal::Parsing::Option
