#pragma once

#include <any>
#include <set>
#include <string>
#include <utility>

#include "core_server/internal/ceql/query/from.hpp"
#include "core_server/internal/coordination/catalog.hpp"
#include "core_server/internal/parsing/ceql_query/autogenerated/CEQLQueryParser.h"
#include "core_server/internal/parsing/ceql_query/autogenerated/CEQLQueryParserBaseVisitor.h"
#include "core_server/internal/parsing/ceql_query/error_handling_utils.hpp"

namespace CORE::Internal::Parsing {
class FromVisitor : public CEQLQueryParserBaseVisitor {
 private:
  std::set<std::string> streams;
  Catalog& catalog;

 public:
  FromVisitor(Catalog& catalog) : catalog(catalog) {}

  CEQL::From get_parsed_from() {
    check_if_streams_names_are_in_catalog(catalog, streams);
    return CEQL::From(std::move(streams));
  }

  virtual std::any visitCore_query(CEQLQueryParser::Core_queryContext* ctx) override {
    // Visiting From clause will identify all streams.
    auto from_ctx = ctx->from_clause();
    if (from_ctx) {
      visit(from_ctx);
    }
    return {};  // Only interested in stream names
  }

  virtual std::any visitStream_name(CEQLQueryParser::Stream_nameContext* ctx) override {
    streams.insert(ctx->getText());
    return {};
  }
};
}  // namespace CORE::Internal::Parsing
