#pragma once

#include <memory>

#include "core_server/internal/ceql/query/partition_by.hpp"
#include "core_server/internal/parsing/ceql_query/autogenerated/CEQLQueryParserBaseVisitor.h"

namespace CORE::Internal::Parsing {
class PartitionByVisitor : public CEQLQueryParserBaseVisitor {
 private:
  std::vector<CEQL::Attribute> attributes = {};

 public:
  CEQL::PartitionBy get_parsed_partition_by() {
    return CEQL::PartitionBy(std::move(attributes));
  }

  virtual std::any visitCore_query(CEQLQueryParser::Core_queryContext* ctx) override {
    if (ctx->partition_list()) visit(ctx->partition_list());
    return {};
  }

  virtual std::any
  visitAttribute_name(CEQLQueryParser::Attribute_nameContext* ctx) override {
    attributes.emplace_back(ctx->getText());
    return {};
  }
};
}  // namespace CORE::Internal::Parsing
