#include "core_server/internal/ceql/query/select.hpp"
#include "core_server/internal/parsing/ceql_query/autogenerated/CEQL_QUERYBaseVisitor.h"

using namespace InternalCORECEQL;

class SelectVisitor : public CEQL_QUERYBaseVisitor {
 private:
  Select::Strategy strategy = Select::Strategy::DEFAULT;
  std::set<std::string> variable_names;
  bool is_star;

 public:
  Select get_parsed_select() {
    return Select(std::move(strategy), std::move(variable_names),
                  std::move(is_star));
  }

  virtual std::any visitCore_query(
      CEQL_QUERYParser::Core_queryContext* ctx) override {
    std::string selectionStrategy;
    std::vector<std::string> eventNames;

    // Visiting Selection Strategy will update the strategy.
    auto selection_strategy_ctx = ctx->selection_strategy();
    if (selection_strategy_ctx) {
      visit(selection_strategy_ctx);
    }

    // Visiting result_values will add all variable_names
    visit(ctx->list_of_variables());

    return {};  // Only interested in Select.
  }

  virtual std::any visitS_star(
      CEQL_QUERYParser::S_starContext* ctx) override {
    is_star = true;
    return {};
  }

  virtual std::any visitAny_name(
      CEQL_QUERYParser::Any_nameContext* ctx) override {
    variable_names.insert(ctx->getText());
    return {};
  }

  virtual std::any visitSs_all(
      CEQL_QUERYParser::Ss_allContext* ctx) override {
    strategy = Select::Strategy::ALL;
    return {};
  }

  virtual std::any visitSs_any(
      CEQL_QUERYParser::Ss_anyContext* ctx) override {
    strategy = Select::Strategy::ANY;
    return {};
  }

  virtual std::any visitSs_last(
      CEQL_QUERYParser::Ss_lastContext* ctx) override {
    strategy = Select::Strategy::LAST;
    return {};
  }

  virtual std::any visitSs_max(
      CEQL_QUERYParser::Ss_maxContext* ctx) override {
    strategy = Select::Strategy::MAX;
    return {};
  }

  virtual std::any visitSs_next(
      CEQL_QUERYParser::Ss_nextContext* ctx) override {
    strategy = Select::Strategy::NEXT;
    return {};
  }

  virtual std::any visitSs_strict(
      CEQL_QUERYParser::Ss_strictContext* ctx) override {
    strategy = Select::Strategy::STRICT;
    return {};
  }
};
