#pragma once

// Shared helpers for the minterm-tree unit tests.
//
// The core idea of every test here is *parity*: build the baseline
// Evaluation::PredicateEvaluator and the MintermTreeEvaluator from the very
// same predicates, feed both the same events, and require identical Bitsets.
// The minterm tree is only an optimization, so any difference is a bug.

#include <ANTLRInputStream.h>
#include <CommonTokenStream.h>
#include <tree/ParseTree.h>

#include <catch2/catch_message.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cstdint>
#include <iostream>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <utility>
#include <vector>

#include "core_server/internal/ceql/cel_formula/formula/projection_formula.hpp"
#include "core_server/internal/ceql/query/consume_by.hpp"
#include "core_server/internal/ceql/query/from.hpp"
#include "core_server/internal/ceql/query/limit.hpp"
#include "core_server/internal/ceql/query/partition_by.hpp"
#include "core_server/internal/ceql/query/query.hpp"
#include "core_server/internal/ceql/query/select.hpp"
#include "core_server/internal/ceql/query/within.hpp"
#include "core_server/internal/ceql/query_transformer/annotate_predicates_with_new_physical_predicates.hpp"
#include "core_server/internal/coordination/catalog.hpp"
#include "core_server/internal/coordination/query_catalog.hpp"
#include "core_server/internal/evaluation/physical_predicate/compare_with_constant.hpp"
#include "core_server/internal/evaluation/physical_predicate/comparison_type.hpp"
#include "core_server/internal/evaluation/physical_predicate/physical_predicate.hpp"
#include "core_server/internal/evaluation/predicate_evaluator.hpp"
#include "core_server/internal/optimizations/minterm_tree/minterm_tree_evaluator.hpp"
#include "core_server/internal/optimizations/minterm_tree/tree_printing.hpp"
#include "core_server/internal/parsing/ceql_query/autogenerated/CEQLQueryLexer.h"
#include "core_server/internal/parsing/ceql_query/autogenerated/CEQLQueryParser.h"
#include "core_server/internal/parsing/ceql_query/visitors/from_visitor.hpp"
#include "core_server/internal/parsing/ceql_query/visitors/where_visitor.hpp"
#include "shared/datatypes/catalog/attribute_info.hpp"
#include "shared/datatypes/catalog/datatypes.hpp"
#include "shared/datatypes/catalog/stream_info.hpp"
#include "shared/datatypes/event.hpp"
#include "shared/datatypes/eventWrapper.hpp"
#include "shared/datatypes/value.hpp"

namespace CORE::Internal::Optimizations::MintermTree::UnitTests {

// ---------------------------------------------------------------------------
// Events for hand-built predicates (no catalog involved).
// All of them are unique event type 0.
// ---------------------------------------------------------------------------

// One int64_t attribute at position 0.
inline Types::EventWrapper make_int_event(int64_t integer_val) {
  auto event = std::make_shared<Types::Event>(0,
                                              std::vector<std::shared_ptr<Types::Value>>{
                                                std::make_unique<Types::IntValue>(
                                                  integer_val)});
  return Types::EventWrapper(std::move(event));
}

// One double attribute at position 0.
inline Types::EventWrapper make_double_event(double double_val) {
  auto event = std::make_shared<Types::Event>(0,
                                              std::vector<std::shared_ptr<Types::Value>>{
                                                std::make_unique<Types::DoubleValue>(
                                                  double_val)});
  return Types::EventWrapper(std::move(event));
}

// An int64_t at position 0 and a string at position 1.
inline Types::EventWrapper
make_int_and_string_event(int64_t integer_val, std::string str_val) {
  auto event = std::make_shared<Types::Event>(
    0,
    std::vector<std::shared_ptr<Types::Value>>{std::make_unique<Types::IntValue>(
                                                 integer_val),
                                               std::make_unique<Types::StringValue>(
                                                 str_val)});
  return Types::EventWrapper(std::move(event));
}

// Hand-built atom on attribute 0 of event type 0: `attribute <Comp> threshold`.
template <CEA::ComparisonType Comp>
std::unique_ptr<CEA::PhysicalPredicate> compare_int(int64_t threshold) {
  return std::make_unique<CEA::CompareWithConstant<Comp, int64_t>>(0, 0, threshold);
}

template <CEA::ComparisonType Comp>
std::unique_ptr<CEA::PhysicalPredicate> compare_double(double threshold) {
  return std::make_unique<CEA::CompareWithConstant<Comp, double>>(0, 0, threshold);
}

inline std::unique_ptr<CEA::PhysicalPredicate> greater_than(int64_t threshold) {
  return compare_int<CEA::ComparisonType::GREATER>(threshold);
}

inline std::unique_ptr<CEA::PhysicalPredicate> less_than(int64_t threshold) {
  return compare_int<CEA::ComparisonType::LESS>(threshold);
}

// ---------------------------------------------------------------------------
// The CEQL fixture catalog: stream S with two events.
//   event1 (unique event type 0): String, Integer1, Integer2, Double1, Double2
//   event2 (unique event type 1): Integer1, Integer2
// Note that Integer1 is attribute position 1 in event1 but position 0 in
// event2, which is exactly what makes weakly-typed atoms (resolved by
// attribute *name*) interesting.
// ---------------------------------------------------------------------------

inline std::vector<Types::AttributeInfo> attributes_of_event_type_1() {
  std::vector<Types::AttributeInfo> attributes_info;
  attributes_info.emplace_back("String", Types::ValueTypes::STRING_VIEW);
  attributes_info.emplace_back("Integer1", Types::ValueTypes::INT64);
  attributes_info.emplace_back("Integer2", Types::ValueTypes::INT64);
  attributes_info.emplace_back("Double1", Types::ValueTypes::DOUBLE);
  attributes_info.emplace_back("Double2", Types::ValueTypes::DOUBLE);
  return attributes_info;
}

inline std::vector<Types::AttributeInfo> attributes_of_event_type_2() {
  std::vector<Types::AttributeInfo> attributes_info;
  attributes_info.emplace_back("Integer1", Types::ValueTypes::INT64);
  attributes_info.emplace_back("Integer2", Types::ValueTypes::INT64);
  return attributes_info;
}

inline Types::EventWrapper
make_event_type_1(std::string val1, int64_t val2, int64_t val3, double val4, double val5) {
  auto event = std::make_shared<Types::Event>(
    0,
    std::vector<std::shared_ptr<Types::Value>>{std::make_unique<Types::StringValue>(val1),
                                               std::make_unique<Types::IntValue>(val2),
                                               std::make_unique<Types::IntValue>(val3),
                                               std::make_unique<Types::DoubleValue>(val4),
                                               std::make_unique<Types::DoubleValue>(val5)});
  return Types::EventWrapper(std::move(event));
}

inline Types::EventWrapper make_event_type_2(int64_t val1, int64_t val2) {
  auto event = std::make_shared<Types::Event>(
    1,
    std::vector<std::shared_ptr<Types::Value>>{std::make_unique<Types::IntValue>(val1),
                                               std::make_unique<Types::IntValue>(val2)});
  return Types::EventWrapper(std::move(event));
}

// Wraps a FILTER clause into a full CEQL query over the fixture stream.
// `event1[...]` / `event2[...]` are strongly typed (a real event name), while
// `X[...]` / `Y[...]` are AS-variables that match no event name, so they take
// the weakly-typed path (attributes resolved by name at runtime).
inline std::string create_query(std::string filter_clause) {
  // clang-format off
  return "SELECT ALL * \n"
         "FROM S\n"
         "WHERE S>event1 as X; S>event2 as Y\n"
         "FILTER\n"
         + filter_clause + "\n"
         "WITHIN 4 EVENTS\n";
  // clang-format on
}

inline void process_catalog(Catalog& catalog) {
  Types::StreamInfo stream_info = catalog.add_stream_type(
    {"S",
     {{"event1", attributes_of_event_type_1()}, {"event2", attributes_of_event_type_2()}}});
  (void)stream_info;
}

// Parses only the FROM and WHERE parts, which is all predicate creation needs.
inline CEQL::Query parse_query(std::string query, Catalog& catalog) {
  antlr4::ANTLRInputStream input(query);
  CEQLQueryLexer lexer(&input);
  antlr4::CommonTokenStream tokens(&lexer);
  CEQLQueryParser parser(&tokens);
  antlr4::tree::ParseTree* tree = parser.parse();

  Parsing::FromVisitor from_visitor(catalog);
  from_visitor.visit(tree);
  CEQL::From from = from_visitor.get_parsed_from();
  std::set<std::string>& streams = from.streams;
  std::map<std::string, std::vector<Types::EventInfo>>
    streams_events = Parsing::get_streams_events_map(catalog, streams);

  Parsing::WhereVisitor where_visitor(catalog, streams_events);
  where_visitor.visit(tree);
  std::unique_ptr<CEQL::ProjectionFormula> formula = std::make_unique<
    CEQL::ProjectionFormula>(std::set<std::string>{""},
                             std::set<std::pair<std::string, std::string>>{});

  CEQL::Query parsed_query(
    CEQL::Select(CEQL::Select::Strategy::ALL, true, std::move(formula), {}, {}),
    CEQL::From({"S"}),
    std::move(where_visitor.get_parsed_where()),
    CEQL::PartitionBy(),
    CEQL::Within(),
    CEQL::ConsumeBy(),
    CEQL::Limit());
  return parsed_query;
}

// Runs the same transformer the engine uses, giving the real physical
// predicates (one bit each, in the engine's bit order).
inline std::vector<std::unique_ptr<CEA::PhysicalPredicate>>
get_predicates(CEQL::Query& query, QueryCatalog& query_catalog) {
  CEQL::AnnotatePredicatesWithNewPhysicalPredicates transformer(query_catalog);
  query = transformer(std::move(query));
  return std::move(transformer.physical_predicates);
}

// ---------------------------------------------------------------------------
// Parity checkers
// ---------------------------------------------------------------------------

// Holds a baseline PredicateEvaluator and a MintermTreeEvaluator built from
// the same predicate objects.
class ParityChecker {
 public:
  Evaluation::PredicateEvaluator baseline;
  MintermTreeEvaluator minterm;

  explicit ParityChecker(
    std::vector<std::unique_ptr<CEA::PhysicalPredicate>>&& predicates,
    size_t max_leaves_per_tree = MintermTreeEvaluator::kMaxLeavesPerTree)
      : baseline(std::move(predicates)),
        minterm(baseline.predicates, max_leaves_per_tree) {
    // Debugging aid: CORE_PRINT_MINTERM_TREES=1 shows the trees every test builds.
    if (print_trees_requested()) {
      std::cout << "\n" << minterm.trees_to_string() << std::endl;
    }
  }

  // Requires both evaluators to produce the same Bitset for `event`.
  void check(Types::EventWrapper& event, const std::string& label = "") {
    Bitset expected = baseline(event);
    Bitset actual = minterm(event);
    INFO("event: " << label);
    INFO("baseline bitset:     " << expected.to_string());
    INFO("minterm tree bitset: " << actual.to_string());
    REQUIRE(actual == expected);
  }
};

// Same as ParityChecker but for a query written in CEQL: it owns the catalog,
// the parsed query and the QueryCatalog (predicates keep references into
// them), so the real compiled predicates stay valid for the checker's life.
class CeqlParityChecker {
  Catalog catalog_;
  CEQL::Query query_;
  QueryCatalog query_catalog_;

 public:
  ParityChecker checker;

  explicit CeqlParityChecker(const std::string& filter_clause)
      : query_([&] {
          process_catalog(catalog_);
          return parse_query(create_query(filter_clause), catalog_);
        }()),
        query_catalog_(catalog_, query_),
        checker(get_predicates(query_, query_catalog_)) {}

  CeqlParityChecker(const CeqlParityChecker&) = delete;
  CeqlParityChecker& operator=(const CeqlParityChecker&) = delete;

  void check(Types::EventWrapper& event, const std::string& label = "") {
    checker.check(event, label);
  }
};

}  // namespace CORE::Internal::Optimizations::MintermTree::UnitTests
