import asyncio
import base64
import hashlib
import hmac
import json
import os
import time

import _pycore
import websockets
from dateutil.parser import isoparse

API_KEY = str(os.environ.get("API_KEY"))
PASSPHRASE = str(os.environ.get("PASSPHRASE"))
SECRET_KEY = str(os.environ.get("SECRET_KEY"))

URI = "wss://ws-feed.exchange.coinbase.com"
SIGNATURE_PATH = "/users/self/verify"

channel = "level2"


async def generate_signature():
    timestamp = str(time.time())
    message = f"{timestamp}GET{SIGNATURE_PATH}"
    hmac_key = base64.b64decode(SECRET_KEY)
    signature = hmac.new(
        hmac_key, message.encode("utf-8"), digestmod=hashlib.sha256
    ).digest()
    signature_b64 = base64.b64encode(signature).decode().rstrip("\n")
    return signature_b64, timestamp


rfq_matches = {
    "type": "subscribe",
    "channels": [
        {
            "name": "rfq_matches",
            "product_ids": [
                "",
            ],
        },
    ],
}

matches = {
    "type": "subscribe",
    "product_ids": [
        "QUICK-USD",
        "SNX-GBP",
        "OOKI-USD",
        "UNI-EUR",
        "MANA-ETH",
        "MONA-USD",
        "QSP-USDT",
        "ATOM-BTC",
        "XYO-USDT",
        "POWR-EUR",
        "ENJ-USDT",
        "DDX-EUR",
        "CGLD-BTC",
        "CRO-USDT",
        "DNT-USDC",
        "WAXL-USD",
        "MATH-USDT",
        "CVX-USD",
        "BTRST-USDT",
        "BLZ-USD",
        "MNDE-USD",
        "DYP-USDT",
        "RPL-USD",
        "KEEP-USD",
        "UMA-GBP",
        "SNX-BTC",
        "RONIN-USD",
        "HNT-USD",
        "GMT-USDT",
        "ETH-USDT",
        "IOTX-EUR",
        "ALGO-USD",
        "MATH-USD",
        "NMR-EUR",
        "CRV-BTC",
        "LINK-USDT",
        "DOT-EUR",
        "RSR-USD",
        "STX-USD",
        "MPL-USD",
        "CAKE-USD",
        "MEDIA-USD",
        "BTC-USD",
        "VOXEL-USD",
        "MUSD-USD",
        "WIF-USD",
        "ZETACHAIN-USD",
        "NCT-EUR",
        "LTC-EUR",
        "XRP-USD",
        "DNT-USD",
        "AXS-USD",
        "C98-USD",
        "MOG-USD",
        "HFT-USD",
        "DIA-USDT",
        "CHZ-EUR",
        "DOT-USD",
        "FORT-USDT",
        "ZEC-USDC",
        "MINA-EUR",
        "CELR-USD",
        "TRAC-USDT",
        "FIDA-USDT",
        "MASK-EUR",
        "AIOZ-USDT",
        "CRPT-USD",
        "FIS-USDT",
        "ARPA-USD",
        "RED-USD",
        "XCN-USDT",
        "LQTY-USDT",
        "COVAL-USD",
        "SXT-USD",
        "BOND-USD",
        "XLM-USD",
        "BAND-EUR",
        "EOS-BTC",
        "SUI-USD",
        "AXS-USDT",
        "C98-USDT",
        "OMNI-USD",
        "MSOL-USD",
        "BNT-EUR",
        "XRP-BTC",
        "XRP-USDT",
        "SUSHI-BTC",
        "1INCH-GBP",
        "ALEPH-USD",
        "KRL-USDT",
        "KRL-USD",
        "CLV-GBP",
        "POLS-USD",
        "ENS-USD",
        "GALA-USDT",
        "LSETH-ETH",
        "GALA-EUR",
        "SHPING-EUR",
        "YFI-BTC",
        "MANA-EUR",
        "ETHFI-USD",
        "RLY-EUR",
        "LCX-EUR",
        "RNDR-USD",
        "AKT-USD",
        "GALA-USD",
        "BTRST-BTC",
        "TURBO-USD",
        "PUNDIX-USD",
        "SHPING-USDT",
        "ACS-USD",
        "COMP-BTC",
        "YFII-USD",
        "PERP-EUR",
        "TIME-USD",
        "GFI-USD",
        "ETH-USD",
        "SWELL-USD",
        "CTSI-USD",
        "QSP-USD",
        "AVAX-USD",
        "LPT-USD",
        "MANTLE-USD",
        "TRU-USDT",
        "GNT-USDC",
        "OMG-BTC",
        "APE-EUR",
        "OMG-GBP",
        "CGLD-USD",
        "CGLD-EUR",
        "LTC-GBP",
        "NCT-USDT",
        "BNT-GBP",
        "SKL-GBP",
        "IP-USD",
        "RLC-BTC",
        "CRO-EUR",
        "AUCTION-USDT",
        "CTX-USDT",
        "ZRO-USD",
        "POL-USD",
        "TRB-USD",
        "BADGER-USD",
        "SHPING-USD",
        "ZRX-BTC",
        "NEAR-USDT",
        "ACH-USDT",
        "QNT-USD",
        "TIME-USDT",
        "CTSI-BTC",
        "SOL-BTC",
        "KNC-BTC",
        "COOKIE-USD",
        "SNX-USD",
        "COW-USD",
        "LCX-USDT",
        "ICP-USD",
        "PIRATE-USD",
        "BTC-USDT",
        "AXS-BTC",
        "KARRAT-USD",
        "UMA-EUR",
        "CLV-USDT",
        "FIDA-EUR",
        "PRIME-USD",
        "SHIB-GBP",
        "DOGE-BTC",
        "OP-USDT",
        "LOOM-USD",
        "REN-USD",
        "ONDO-USD",
        "REQ-USD",
        "ABT-USD",
        "MIR-USD",
        "LRDS-USD",
        "PENGU-USD",
        "PROMPT-USD",
        "SYLO-USDT",
        "GRT-GBP",
        "BAL-BTC",
        "PYR-USD",
        "ASM-USD",
        "RAD-USD",
        "REN-BTC",
        "NEON-USD",
        "PEPE-USD",
        "ATOM-EUR",
        "REQ-GBP",
        "SOL-ETH",
        "XTZ-GBP",
        "ADA-USDT",
        "DIA-USD",
        "NU-BTC",
        "IOTX-USD",
        "AXL-USD",
        "BNT-USD",
        "LIT-USD",
        "ICP-EUR",
        "QI-USD",
        "ALICE-USD",
        "ATA-USDT",
        "ZEN-USDT",
        "BTC-USDC",
        "LQTY-USD",
        "ETC-USD",
        "KNC-USD",
        "BLAST-USD",
        "DOGE-GBP",
        "FARTCOIN-USD",
        "TRUMP-USD",
        "FARM-USDT",
        "ANT-USD",
        "FIL-EUR",
        "REP-BTC",
        "ZEN-USD",
        "FORTH-GBP",
        "PNG-USD",
        "EOS-EUR",
        "MLN-USD",
        "SQD-USD",
        "MORPHO-USD",
        "STORJ-BTC",
        "UNI-GBP",
        "SEAM-USD",
        "A8-USD",
        "GAL-USDT",
        "L3-USD",
        "SUSHI-ETH",
        "BTC-EUR",
        "WBTC-USD",
        "USDT-USD",
        "TRU-BTC",
        "ANKR-EUR",
        "SHIB-USD",
        "LINK-USD",
        "PLA-USD",
        "VARA-USD",
        "SOL-USDT",
        "FORT-USD",
        "FAI-USD",
        "BTRST-GBP",
        "DDX-USD",
        "XYO-BTC",
        "REZ-USD",
        "RENDER-USD",
        "USDT-EUR",
        "XRP-EUR",
        "SKL-BTC",
        "FET-USDT",
        "HBAR-USDT",
        "ATOM-GBP",
        "RAD-USDT",
        "LINK-BTC",
        "MATIC-USDT",
        "VET-USD",
        "FOX-USDT",
        "TRU-EUR",
        "ADA-GBP",
        "RAD-EUR",
        "RLY-USD",
        "TRAC-EUR",
        "FX-USD",
        "DOT-USDT",
        "RBN-USD",
        "BNT-BTC",
        "ACH-USD",
        "ORN-BTC",
        "ETH-DAI",
        "SPA-USD",
        "BCH-BTC",
        "MATIC-BTC",
        "SHIB-USDT",
        "ARPA-EUR",
        "REP-USD",
        "AUDIO-USD",
        "LTC-BTC",
        "DESO-USD",
        "TRB-BTC",
        "AVAX-USDT",
        "RAD-BTC",
        "ENS-USDT",
        "UPI-USD",
        "KEYCAT-USD",
        "HIGH-USD",
        "XRP-GBP",
        "BAND-USD",
        "UMA-BTC",
        "TIA-USD",
        "LDO-USD",
        "WAMPL-USDT",
        "BIT-USDT",
        "REQ-BTC",
        "RLC-USD",
        "DIMO-USD",
        "UST-EUR",
        "DRIFT-USD",
        "SAFE-USD",
        "FIS-USD",
        "FLR-USD",
        "UPI-USDT",
        "BICO-USD",
        "PRO-USD",
        "NMR-USD",
        "WCFG-BTC",
        "HOPR-USD",
        "OP-USD",
        "MULTI-USD",
        "SUSHI-EUR",
        "SWFTC-USD",
        "ZETA-USD",
        "NMR-BTC",
        "HONEY-USD",
        "MCO2-USDT",
        "TONE-USD",
        "VGX-USDT",
        "BIGTIME-USD",
        "LSETH-USD",
        "DEGEN-USD",
        "GMT-USD",
        "SUKU-EUR",
        "APE-USD",
        "XCN-USD",
        "NU-GBP",
        "PNUT-USD",
        "PYUSD-USD",
        "PRQ-USD",
        "BOBA-USDT",
        "CLV-EUR",
        "MATIC-USD",
        "AVAX-EUR",
        "USDT-USDC",
        "CGLD-GBP",
        "UST-USDT",
        "NKN-EUR",
        "BAT-ETH",
        "PAX-USD",
        "LRC-USD",
        "KSM-USD",
        "IDEX-USDT",
        "COTI-USD",
        "NKN-USD",
        "AGLD-USD",
        "IO-USD",
        "TOSHI-USD",
        "INJ-USD",
        "NKN-GBP",
        "BERA-USD",
        "VVV-USD",
        "DASH-BTC",
        "JTO-USD",
        "USDT-GBP",
        "KRL-EUR",
        "AAVE-GBP",
        "ETH-EUR",
        "BAND-BTC",
        "RLY-GBP",
        "PENDLE-USD",
        "NEST-USD",
        "BLUR-USD",
        "UMA-USD",
        "ZEC-BTC",
        "FLOKI-USD",
        "SOL-GBP",
        "ZORA-USD",
        "PLU-USD",
        "OSMO-USD",
        "FARM-USD",
        "WLUNA-USDT",
        "STORJ-USD",
        "GODS-USD",
        "EURC-USDC",
        "OGN-BTC",
        "ENA-USD",
        "RARE-USD",
        "APT-USD",
        "INDEX-USDT",
        "ALGO-BTC",
        "AERGO-USD",
        "DAI-USDC",
        "RNDR-USDT",
        "LINK-EUR",
        "SUSHI-GBP",
        "STG-USD",
        "SYRUP-USD",
        "AIOZ-USD",
        "CVC-USDC",
        "OMG-EUR",
        "HFT-USDT",
        "ANKR-GBP",
        "ENJ-USD",
        "BUSD-USD",
        "EOS-USD",
        "PYTH-USD",
        "DREP-USD",
        "ROSE-USDT",
        "MOODENG-USD",
        "METIS-USDT",
        "POWR-USD",
        "ADA-ETH",
        "FORTH-BTC",
        "MINA-USDT",
        "VELO-USD",
        "UNFI-USD",
        "WAMPL-USD",
        "POWR-USDT",
        "DESO-EUR",
        "LCX-USD",
        "MATIC-EUR",
        "POLY-USD",
        "MIR-GBP",
        "ENS-EUR",
        "IDEX-USD",
        "ATOM-USDT",
        "GRT-BTC",
        "G-USD",
        "OMG-USD",
        "WCFG-EUR",
        "KERNEL-USD",
        "DOGE-USD",
        "MIR-BTC",
        "CRO-USD",
        "XLM-USDT",
        "XLM-BTC",
        "SKL-USD",
        "DAI-USD",
        "CLANKER-USD",
        "FIL-BTC",
        "BCH-USD",
        "ELA-USDT",
        "CORECHAIN-USD",
        "AVT-USD",
        "FIL-USD",
        "MOBILE-USD",
        "ETC-EUR",
        "POLS-USDT",
        "DAR-USD",
        "LRC-BTC",
        "ETH-GBP",
        "ICP-USDT",
        "LOOM-USDC",
        "ADA-BTC",
        "LOKA-USD",
        "SAND-USDT",
        "AUCTION-EUR",
        "ETH-BTC",
        "GNO-USD",
        "MDT-USDT",
        "AST-USD",
        "NEST-USDT",
        "ICP-BTC",
        "MTL-USD",
        "ADA-USDC",
        "IMX-USDT",
        "MUSE-USD",
        "SAND-USD",
        "ZEN-BTC",
        "AURORA-USD",
        "HBAR-USD",
        "EURC-USD",
        "INDEX-USD",
        "CRV-EUR",
        "FOX-USD",
        "FET-USD",
        "HOPR-USDT",
        "LQTY-EUR",
        "TRU-USD",
        "SNT-USD",
        "DOT-BTC",
        "AUCTION-USD",
        "ANKR-USD",
        "DIA-EUR",
        "ALGO-GBP",
        "BAL-USD",
        "MASK-GBP",
        "MKR-USD",
        "UNI-USD",
        "EIGEN-USD",
        "ICP-GBP",
        "AAVE-BTC",
        "SNX-EUR",
        "MCO2-USD",
        "ORN-USD",
        "DESO-USDT",
        "TRAC-USD",
        "CRV-GBP",
        "BTRST-EUR",
        "WLUNA-USD",
        "ETC-BTC",
        "OGN-USD",
        "XYO-USD",
        "ACX-USD",
        "BICO-USDT",
        "ATH-USD",
        "ALT-USD",
        "COMP-USD",
        "LRC-USDT",
        "FLOW-USDT",
        "PERP-USDT",
        "1INCH-BTC",
        "NKN-BTC",
        "T-USD",
        "ILV-USD",
        "USDC-EUR",
        "ELA-USD",
        "TRIBE-USD",
        "CLV-USD",
        "DOGE-EUR",
        "DDX-USDT",
        "GIGA-USD",
        "MAGIC-USD",
        "BCH-GBP",
        "ERN-USDT",
        "CTX-EUR",
        "BTRST-USD",
        "MINA-USD",
        "BAT-BTC",
        "KAITO-USD",
        "STX-USDT",
        "API3-USDT",
        "ME-USD",
        "GRT-EUR",
        "ENJ-BTC",
        "SYLO-USD",
        "RARI-USD",
        "XYO-EUR",
        "EGLD-USD",
        "SKL-EUR",
        "ETH-USDC",
        "BADGER-USDT",
        "EURC-EUR",
        "SPELL-USD",
        "RAD-GBP",
        "BTC-GBP",
        "BOBA-USD",
        "ATOM-USD",
        "USDC-GBP",
        "PRQ-USDT",
        "CHZ-GBP",
        "SEI-USD",
        "ERN-EUR",
        "BCH-EUR",
        "MDT-USD",
        "ORCA-USD",
        "SUPER-USDT",
        "ALCX-USDT",
        "REQ-USDT",
        "DOGINME-USD",
        "JASMY-USDT",
        "ARB-USD",
        "POPCAT-USD",
        "BOND-USDT",
        "BADGER-EUR",
        "ROSE-USD",
        "POND-USDT",
        "GNO-USDT",
        "CTX-USD",
        "CHZ-USD",
        "GLM-USD",
        "APT-USDT",
        "KSM-USDT",
        "1INCH-EUR",
        "UST-USD",
        "NEAR-USD",
        "PERP-USD",
        "FLOW-USD",
        "ORN-USDT",
        "DYP-USD",
        "ALEO-USD",
        "APE-USDT",
        "TVK-USD",
        "MANA-USD",
        "NU-EUR",
        "SUKU-USD",
        "GRT-USD",
        "ZEC-USD",
        "VGX-USD",
        "RNDR-EUR",
        "POLY-USDT",
        "DOT-GBP",
        "CHZ-USDT",
        "ASM-USDT",
        "GTC-USD",
        "XTZ-BTC",
        "ARPA-USDT",
        "ADA-USD",
        "WCFG-USD",
        "CBETH-ETH",
        "WLUNA-EUR",
        "GAL-USD",
        "CRV-USD",
        "BIT-USD",
        "FORTH-USD",
        "MANA-USDC",
        "SPELL-USDT",
        "BAND-GBP",
        "KAVA-USD",
        "VGX-EUR",
        "MASK-USD",
        "ALGO-EUR",
        "FIDA-USD",
        "BONK-USD",
        "BAT-USDC",
        "MEDIA-USDT",
        "00-USD",
        "SUPER-USD",
        "PAX-USDT",
        "SHDW-USD",
        "YFI-USD",
        "VTHO-USD",
        "DOGE-USDT",
        "AAVE-USD",
        "GST-USD",
        "DREP-USDT",
        "LTC-USD",
        "JASMY-USD",
        "AXS-EUR",
        "DASH-USD",
        "NMR-GBP",
        "ALCX-EUR",
        "LINK-GBP",
        "COVAL-USDT",
        "STG-USDT",
        "WELL-USD",
        "LA-USD",
        "JUP-USD",
        "TAO-USD",
        "NU-USD",
        "GYEN-USD",
        "RLY-USDT",
        "ZRX-USD",
        "ALCX-USD",
        "AAVE-EUR",
        "MOVE-USD",
        "XTZ-USD",
        "MATIC-GBP",
        "MANA-BTC",
        "ERN-USD",
        "NCT-USD",
        "BICO-EUR",
        "OCEAN-USD",
        "DEXT-USD",
        "MXC-USD",
        "SOL-USD",
        "API3-USD",
        "PAXG-USD",
        "QNT-USDT",
        "ATA-USD",
        "OXT-USD",
        "MKR-BTC",
        "SUKU-USDT",
        "PRCL-USD",
        "CVC-USD",
        "ANKR-BTC",
        "AGLD-USDT",
        "XTZ-EUR",
        "AERO-USD",
        "SHIB-EUR",
        "GUSD-USD",
        "1INCH-USD",
        "CBETH-USD",
        "METIS-USD",
        "HOME-USD",
        "WLD-USD",
        "TNSR-USD",
        "IMX-USD",
        "UNI-BTC",
        "MIR-EUR",
        "ZRX-EUR",
        "WBTC-BTC",
        "BAT-USD",
        "ZK-USD",
        "POND-USD",
        "AMP-USD",
        "ADA-EUR",
        "SD-USD",
        "WLUNA-GBP",
        "INV-USD",
        "RGT-USD",
        "LINK-ETH",
        "MASK-USDT",
        "ETC-GBP",
        "REQ-EUR",
        "XLM-EUR",
        "WCFG-USDT",
        "ARKM-USD",
        "B3-USD",
        "STRK-USD",
        "AVAX-BTC",
        "EDGE-USD",
        "BAT-EUR",
        "SUSHI-USD",
        "FORTH-EUR",
        "RAI-USD",
        "SOL-EUR",
        "GHST-USD",
        "SYN-USD",
        "FIL-GBP",
    ],
    "channels": ["matches"],
}

ticker = {
    "type": "subscribe",
    "product_ids": [
        "QUICK-USD",
        "SNX-GBP",
        "OOKI-USD",
        "UNI-EUR",
        "MANA-ETH",
        "MONA-USD",
        "QSP-USDT",
        "ATOM-BTC",
        "XYO-USDT",
        "POWR-EUR",
        "ENJ-USDT",
        "DDX-EUR",
        "CGLD-BTC",
        "CRO-USDT",
        "DNT-USDC",
        "WAXL-USD",
        "MATH-USDT",
        "CVX-USD",
        "BTRST-USDT",
        "BLZ-USD",
        "MNDE-USD",
        "DYP-USDT",
        "RPL-USD",
        "KEEP-USD",
        "UMA-GBP",
        "SNX-BTC",
        "RONIN-USD",
        "HNT-USD",
        "GMT-USDT",
        "ETH-USDT",
        "IOTX-EUR",
        "ALGO-USD",
        "MATH-USD",
        "NMR-EUR",
        "CRV-BTC",
        "LINK-USDT",
        "DOT-EUR",
        "RSR-USD",
        "STX-USD",
        "MPL-USD",
        "CAKE-USD",
        "MEDIA-USD",
        "BTC-USD",
        "VOXEL-USD",
        "MUSD-USD",
        "WIF-USD",
        "ZETACHAIN-USD",
        "NCT-EUR",
        "LTC-EUR",
        "XRP-USD",
        "DNT-USD",
        "AXS-USD",
        "C98-USD",
        "MOG-USD",
        "HFT-USD",
        "DIA-USDT",
        "CHZ-EUR",
        "DOT-USD",
        "FORT-USDT",
        "ZEC-USDC",
        "MINA-EUR",
        "CELR-USD",
        "TRAC-USDT",
        "FIDA-USDT",
        "MASK-EUR",
        "AIOZ-USDT",
        "CRPT-USD",
        "FIS-USDT",
        "ARPA-USD",
        "RED-USD",
        "XCN-USDT",
        "LQTY-USDT",
        "COVAL-USD",
        "SXT-USD",
        "BOND-USD",
        "XLM-USD",
        "BAND-EUR",
        "EOS-BTC",
        "SUI-USD",
        "AXS-USDT",
        "C98-USDT",
        "OMNI-USD",
        "MSOL-USD",
        "BNT-EUR",
        "XRP-BTC",
        "XRP-USDT",
        "SUSHI-BTC",
        "1INCH-GBP",
        "ALEPH-USD",
        "KRL-USDT",
        "KRL-USD",
        "CLV-GBP",
        "POLS-USD",
        "ENS-USD",
        "GALA-USDT",
        "LSETH-ETH",
        "GALA-EUR",
        "SHPING-EUR",
        "YFI-BTC",
        "MANA-EUR",
        "ETHFI-USD",
        "RLY-EUR",
        "LCX-EUR",
        "RNDR-USD",
        "AKT-USD",
        "GALA-USD",
        "BTRST-BTC",
        "TURBO-USD",
        "PUNDIX-USD",
        "SHPING-USDT",
        "ACS-USD",
        "COMP-BTC",
        "YFII-USD",
        "PERP-EUR",
        "TIME-USD",
        "GFI-USD",
        "ETH-USD",
        "SWELL-USD",
        "CTSI-USD",
        "QSP-USD",
        "AVAX-USD",
        "LPT-USD",
        "MANTLE-USD",
        "TRU-USDT",
        "GNT-USDC",
        "OMG-BTC",
        "APE-EUR",
        "OMG-GBP",
        "CGLD-USD",
        "CGLD-EUR",
        "LTC-GBP",
        "NCT-USDT",
        "BNT-GBP",
        "SKL-GBP",
        "IP-USD",
        "RLC-BTC",
        "CRO-EUR",
        "AUCTION-USDT",
        "CTX-USDT",
        "ZRO-USD",
        "POL-USD",
        "TRB-USD",
        "BADGER-USD",
        "SHPING-USD",
        "ZRX-BTC",
        "NEAR-USDT",
        "ACH-USDT",
        "QNT-USD",
        "TIME-USDT",
        "CTSI-BTC",
        "SOL-BTC",
        "KNC-BTC",
        "COOKIE-USD",
        "SNX-USD",
        "COW-USD",
        "LCX-USDT",
        "ICP-USD",
        "PIRATE-USD",
        "BTC-USDT",
        "AXS-BTC",
        "KARRAT-USD",
        "UMA-EUR",
        "CLV-USDT",
        "FIDA-EUR",
        "PRIME-USD",
        "SHIB-GBP",
        "DOGE-BTC",
        "OP-USDT",
        "LOOM-USD",
        "REN-USD",
        "ONDO-USD",
        "REQ-USD",
        "ABT-USD",
        "MIR-USD",
        "LRDS-USD",
        "PENGU-USD",
        "PROMPT-USD",
        "SYLO-USDT",
        "GRT-GBP",
        "BAL-BTC",
        "PYR-USD",
        "ASM-USD",
        "RAD-USD",
        "REN-BTC",
        "NEON-USD",
        "PEPE-USD",
        "ATOM-EUR",
        "REQ-GBP",
        "SOL-ETH",
        "XTZ-GBP",
        "ADA-USDT",
        "DIA-USD",
        "NU-BTC",
        "IOTX-USD",
        "AXL-USD",
        "BNT-USD",
        "LIT-USD",
        "ICP-EUR",
        "QI-USD",
        "ALICE-USD",
        "ATA-USDT",
        "ZEN-USDT",
        "BTC-USDC",
        "LQTY-USD",
        "ETC-USD",
        "KNC-USD",
        "BLAST-USD",
        "DOGE-GBP",
        "FARTCOIN-USD",
        "TRUMP-USD",
        "FARM-USDT",
        "ANT-USD",
        "FIL-EUR",
        "REP-BTC",
        "ZEN-USD",
        "FORTH-GBP",
        "PNG-USD",
        "EOS-EUR",
        "MLN-USD",
        "SQD-USD",
        "MORPHO-USD",
        "STORJ-BTC",
        "UNI-GBP",
        "SEAM-USD",
        "A8-USD",
        "GAL-USDT",
        "L3-USD",
        "SUSHI-ETH",
        "BTC-EUR",
        "WBTC-USD",
        "USDT-USD",
        "TRU-BTC",
        "ANKR-EUR",
        "SHIB-USD",
        "LINK-USD",
        "PLA-USD",
        "VARA-USD",
        "SOL-USDT",
        "FORT-USD",
        "FAI-USD",
        "BTRST-GBP",
        "DDX-USD",
        "XYO-BTC",
        "REZ-USD",
        "RENDER-USD",
        "USDT-EUR",
        "XRP-EUR",
        "SKL-BTC",
        "FET-USDT",
        "HBAR-USDT",
        "ATOM-GBP",
        "RAD-USDT",
        "LINK-BTC",
        "MATIC-USDT",
        "VET-USD",
        "FOX-USDT",
        "TRU-EUR",
        "ADA-GBP",
        "RAD-EUR",
        "RLY-USD",
        "TRAC-EUR",
        "FX-USD",
        "DOT-USDT",
        "RBN-USD",
        "BNT-BTC",
        "ACH-USD",
        "ORN-BTC",
        "ETH-DAI",
        "SPA-USD",
        "BCH-BTC",
        "MATIC-BTC",
        "SHIB-USDT",
        "ARPA-EUR",
        "REP-USD",
        "AUDIO-USD",
        "LTC-BTC",
        "DESO-USD",
        "TRB-BTC",
        "AVAX-USDT",
        "RAD-BTC",
        "ENS-USDT",
        "UPI-USD",
        "KEYCAT-USD",
        "HIGH-USD",
        "XRP-GBP",
        "BAND-USD",
        "UMA-BTC",
        "TIA-USD",
        "LDO-USD",
        "WAMPL-USDT",
        "BIT-USDT",
        "REQ-BTC",
        "RLC-USD",
        "DIMO-USD",
        "UST-EUR",
        "DRIFT-USD",
        "SAFE-USD",
        "FIS-USD",
        "FLR-USD",
        "UPI-USDT",
        "BICO-USD",
        "PRO-USD",
        "NMR-USD",
        "WCFG-BTC",
        "HOPR-USD",
        "OP-USD",
        "MULTI-USD",
        "SUSHI-EUR",
        "SWFTC-USD",
        "ZETA-USD",
        "NMR-BTC",
        "HONEY-USD",
        "MCO2-USDT",
        "TONE-USD",
        "VGX-USDT",
        "BIGTIME-USD",
        "LSETH-USD",
        "DEGEN-USD",
        "GMT-USD",
        "SUKU-EUR",
        "APE-USD",
        "XCN-USD",
        "NU-GBP",
        "PNUT-USD",
        "PYUSD-USD",
        "PRQ-USD",
        "BOBA-USDT",
        "CLV-EUR",
        "MATIC-USD",
        "AVAX-EUR",
        "USDT-USDC",
        "CGLD-GBP",
        "UST-USDT",
        "NKN-EUR",
        "BAT-ETH",
        "PAX-USD",
        "LRC-USD",
        "KSM-USD",
        "IDEX-USDT",
        "COTI-USD",
        "NKN-USD",
        "AGLD-USD",
        "IO-USD",
        "TOSHI-USD",
        "INJ-USD",
        "NKN-GBP",
        "BERA-USD",
        "VVV-USD",
        "DASH-BTC",
        "JTO-USD",
        "USDT-GBP",
        "KRL-EUR",
        "AAVE-GBP",
        "ETH-EUR",
        "BAND-BTC",
        "RLY-GBP",
        "PENDLE-USD",
        "NEST-USD",
        "BLUR-USD",
        "UMA-USD",
        "ZEC-BTC",
        "FLOKI-USD",
        "SOL-GBP",
        "ZORA-USD",
        "PLU-USD",
        "OSMO-USD",
        "FARM-USD",
        "WLUNA-USDT",
        "STORJ-USD",
        "GODS-USD",
        "EURC-USDC",
        "OGN-BTC",
        "ENA-USD",
        "RARE-USD",
        "APT-USD",
        "INDEX-USDT",
        "ALGO-BTC",
        "AERGO-USD",
        "DAI-USDC",
        "RNDR-USDT",
        "LINK-EUR",
        "SUSHI-GBP",
        "STG-USD",
        "SYRUP-USD",
        "AIOZ-USD",
        "CVC-USDC",
        "OMG-EUR",
        "HFT-USDT",
        "ANKR-GBP",
        "ENJ-USD",
        "BUSD-USD",
        "EOS-USD",
        "PYTH-USD",
        "DREP-USD",
        "ROSE-USDT",
        "MOODENG-USD",
        "METIS-USDT",
        "POWR-USD",
        "ADA-ETH",
        "FORTH-BTC",
        "MINA-USDT",
        "VELO-USD",
        "UNFI-USD",
        "WAMPL-USD",
        "POWR-USDT",
        "DESO-EUR",
        "LCX-USD",
        "MATIC-EUR",
        "POLY-USD",
        "MIR-GBP",
        "ENS-EUR",
        "IDEX-USD",
        "ATOM-USDT",
        "GRT-BTC",
        "G-USD",
        "OMG-USD",
        "WCFG-EUR",
        "KERNEL-USD",
        "DOGE-USD",
        "MIR-BTC",
        "CRO-USD",
        "XLM-USDT",
        "XLM-BTC",
        "SKL-USD",
        "DAI-USD",
        "CLANKER-USD",
        "FIL-BTC",
        "BCH-USD",
        "ELA-USDT",
        "CORECHAIN-USD",
        "AVT-USD",
        "FIL-USD",
        "MOBILE-USD",
        "ETC-EUR",
        "POLS-USDT",
        "DAR-USD",
        "LRC-BTC",
        "ETH-GBP",
        "ICP-USDT",
        "LOOM-USDC",
        "ADA-BTC",
        "LOKA-USD",
        "SAND-USDT",
        "AUCTION-EUR",
        "ETH-BTC",
        "GNO-USD",
        "MDT-USDT",
        "AST-USD",
        "NEST-USDT",
        "ICP-BTC",
        "MTL-USD",
        "ADA-USDC",
        "IMX-USDT",
        "MUSE-USD",
        "SAND-USD",
        "ZEN-BTC",
        "AURORA-USD",
        "HBAR-USD",
        "EURC-USD",
        "INDEX-USD",
        "CRV-EUR",
        "FOX-USD",
        "FET-USD",
        "HOPR-USDT",
        "LQTY-EUR",
        "TRU-USD",
        "SNT-USD",
        "DOT-BTC",
        "AUCTION-USD",
        "ANKR-USD",
        "DIA-EUR",
        "ALGO-GBP",
        "BAL-USD",
        "MASK-GBP",
        "MKR-USD",
        "UNI-USD",
        "EIGEN-USD",
        "ICP-GBP",
        "AAVE-BTC",
        "SNX-EUR",
        "MCO2-USD",
        "ORN-USD",
        "DESO-USDT",
        "TRAC-USD",
        "CRV-GBP",
        "BTRST-EUR",
        "WLUNA-USD",
        "ETC-BTC",
        "OGN-USD",
        "XYO-USD",
        "ACX-USD",
        "BICO-USDT",
        "ATH-USD",
        "ALT-USD",
        "COMP-USD",
        "LRC-USDT",
        "FLOW-USDT",
        "PERP-USDT",
        "1INCH-BTC",
        "NKN-BTC",
        "T-USD",
        "ILV-USD",
        "USDC-EUR",
        "ELA-USD",
        "TRIBE-USD",
        "CLV-USD",
        "DOGE-EUR",
        "DDX-USDT",
        "GIGA-USD",
        "MAGIC-USD",
        "BCH-GBP",
        "ERN-USDT",
        "CTX-EUR",
        "BTRST-USD",
        "MINA-USD",
        "BAT-BTC",
        "KAITO-USD",
        "STX-USDT",
        "API3-USDT",
        "ME-USD",
        "GRT-EUR",
        "ENJ-BTC",
        "SYLO-USD",
        "RARI-USD",
        "XYO-EUR",
        "EGLD-USD",
        "SKL-EUR",
        "ETH-USDC",
        "BADGER-USDT",
        "EURC-EUR",
        "SPELL-USD",
        "RAD-GBP",
        "BTC-GBP",
        "BOBA-USD",
        "ATOM-USD",
        "USDC-GBP",
        "PRQ-USDT",
        "CHZ-GBP",
        "SEI-USD",
        "ERN-EUR",
        "BCH-EUR",
        "MDT-USD",
        "ORCA-USD",
        "SUPER-USDT",
        "ALCX-USDT",
        "REQ-USDT",
        "DOGINME-USD",
        "JASMY-USDT",
        "ARB-USD",
        "POPCAT-USD",
        "BOND-USDT",
        "BADGER-EUR",
        "ROSE-USD",
        "POND-USDT",
        "GNO-USDT",
        "CTX-USD",
        "CHZ-USD",
        "GLM-USD",
        "APT-USDT",
        "KSM-USDT",
        "1INCH-EUR",
        "UST-USD",
        "NEAR-USD",
        "PERP-USD",
        "FLOW-USD",
        "ORN-USDT",
        "DYP-USD",
        "ALEO-USD",
        "APE-USDT",
        "TVK-USD",
        "MANA-USD",
        "NU-EUR",
        "SUKU-USD",
        "GRT-USD",
        "ZEC-USD",
        "VGX-USD",
        "RNDR-EUR",
        "POLY-USDT",
        "DOT-GBP",
        "CHZ-USDT",
        "ASM-USDT",
        "GTC-USD",
        "XTZ-BTC",
        "ARPA-USDT",
        "ADA-USD",
        "WCFG-USD",
        "CBETH-ETH",
        "WLUNA-EUR",
        "GAL-USD",
        "CRV-USD",
        "BIT-USD",
        "FORTH-USD",
        "MANA-USDC",
        "SPELL-USDT",
        "BAND-GBP",
        "KAVA-USD",
        "VGX-EUR",
        "MASK-USD",
        "ALGO-EUR",
        "FIDA-USD",
        "BONK-USD",
        "BAT-USDC",
        "MEDIA-USDT",
        "00-USD",
        "SUPER-USD",
        "PAX-USDT",
        "SHDW-USD",
        "YFI-USD",
        "VTHO-USD",
        "DOGE-USDT",
        "AAVE-USD",
        "GST-USD",
        "DREP-USDT",
        "LTC-USD",
        "JASMY-USD",
        "AXS-EUR",
        "DASH-USD",
        "NMR-GBP",
        "ALCX-EUR",
        "LINK-GBP",
        "COVAL-USDT",
        "STG-USDT",
        "WELL-USD",
        "LA-USD",
        "JUP-USD",
        "TAO-USD",
        "NU-USD",
        "GYEN-USD",
        "RLY-USDT",
        "ZRX-USD",
        "ALCX-USD",
        "AAVE-EUR",
        "MOVE-USD",
        "XTZ-USD",
        "MATIC-GBP",
        "MANA-BTC",
        "ERN-USD",
        "NCT-USD",
        "BICO-EUR",
        "OCEAN-USD",
        "DEXT-USD",
        "MXC-USD",
        "SOL-USD",
        "API3-USD",
        "PAXG-USD",
        "QNT-USDT",
        "ATA-USD",
        "OXT-USD",
        "MKR-BTC",
        "SUKU-USDT",
        "PRCL-USD",
        "CVC-USD",
        "ANKR-BTC",
        "AGLD-USDT",
        "XTZ-EUR",
        "AERO-USD",
        "SHIB-EUR",
        "GUSD-USD",
        "1INCH-USD",
        "CBETH-USD",
        "METIS-USD",
        "HOME-USD",
        "WLD-USD",
        "TNSR-USD",
        "IMX-USD",
        "UNI-BTC",
        "MIR-EUR",
        "ZRX-EUR",
        "WBTC-BTC",
        "BAT-USD",
        "ZK-USD",
        "POND-USD",
        "AMP-USD",
        "ADA-EUR",
        "SD-USD",
        "WLUNA-GBP",
        "INV-USD",
        "RGT-USD",
        "LINK-ETH",
        "MASK-USDT",
        "ETC-GBP",
        "REQ-EUR",
        "XLM-EUR",
        "WCFG-USDT",
        "ARKM-USD",
        "B3-USD",
        "STRK-USD",
        "AVAX-BTC",
        "EDGE-USD",
        "BAT-EUR",
        "SUSHI-USD",
        "FORTH-EUR",
        "RAI-USD",
        "SOL-EUR",
        "GHST-USD",
        "SYN-USD",
        "FIL-GBP",
    ],
    "channels": ["ticker"],
}


## Attributes creators with stream declarations
def create_ticker_attributes(json_response):
    product_id = _pycore.PyStringValue(json_response["product_id"])
    price = _pycore.PyDoubleValue(float(json_response["price"]))
    open_24h = _pycore.PyDoubleValue(float(json_response["open_24h"]))
    volume_24h = _pycore.PyDoubleValue(float(json_response["volume_24h"]))
    low_24h = _pycore.PyDoubleValue(float(json_response["low_24h"]))
    high_24h = _pycore.PyDoubleValue(float(json_response["high_24h"]))
    volume_30d = _pycore.PyDoubleValue(float(json_response["volume_30d"]))
    best_bid = _pycore.PyDoubleValue(float(json_response["best_bid"]))
    best_bid_size = _pycore.PyDoubleValue(float(json_response["best_bid_size"]))
    best_ask = _pycore.PyDoubleValue(float(json_response["best_ask"]))
    best_ask_size = _pycore.PyDoubleValue(float(json_response["best_ask_size"]))
    last_size = _pycore.PyDoubleValue(float(json_response["last_size"]))
    time = _pycore.PyDateValue(int(isoparse(json_response["time"]).timestamp() * 1e9))
    attributes = [
        product_id,
        price,
        open_24h,
        volume_24h,
        low_24h,
        high_24h,
        volume_30d,
        best_bid,
        best_bid_size,
        best_ask,
        best_ask_size,
        last_size,
        time,
    ]

    return attributes


ticker_stream_declaration = """CREATE STREAM TICKER { \n
                        EVENT Buy { product_id:string, price:double, open24h:double, volume_24h:double, low_24h:double, \
                        high_24h:double, volume_30d:double, best_bid:double, best_bid_size:double, best_ask:double, best_ask_size:double, \
                        last_size:double, time:primary_time } \n,
                        EVENT Sell { product_id:string, price:double, open24h:double, volume_24h:double, low_24h:double, \
                        high_24h:double, volume_30d:double, best_bid:double, best_bid_size:double, best_ask:double, best_ask_size:double, \
                        last_size:double, time:primary_time } \n
                        }
                        """


def create_matches_attributes(json_response):
    trade_id = _pycore.PyIntValue(json_response["trade_id"])
    sequence = _pycore.PyIntValue(json_response["sequence"])
    maker_order_id = _pycore.PyStringValue(json_response["maker_order_id"])
    taker_order_id = _pycore.PyStringValue(json_response["taker_order_id"])
    time = _pycore.PyDateValue(int(isoparse(json_response["time"]).timestamp() * 1e9))
    product_id = _pycore.PyStringValue(json_response["product_id"])
    size = _pycore.PyDoubleValue(float(json_response["size"]))
    price = _pycore.PyDoubleValue(float(json_response["price"]))

    attributes = [
        trade_id,
        maker_order_id,
        taker_order_id,
        size,
        price,
        product_id,
        sequence,
        time,
    ]

    return attributes


matches_stream_declaration = """CREATE STREAM Matches { \n
                        EVENT Buy { trade_id:int, maker_order_id:string, taker_order_id:string, \
                        size:double, price:double, product_id:string, sequence:int, time:primary_time } \n,
                        EVENT Sell { trade_id:int, maker_order_id:string, taker_order_id:string, \
                        size:double, price:double, product_id:string, sequence:int, time:primary_time } \n
                        }
                        """


def create_rfq_attributes(json_response):
    maker_order_id = _pycore.PyStringValue(json_response["maker_order_id"])
    taker_order_id = _pycore.PyStringValue(json_response["taker_order_id"])
    time = _pycore.PyDateValue(int(isoparse(json_response["time"]).timestamp() * 1e9))
    trade_id = _pycore.PyIntValue(json_response["trade_id"])
    product_id = _pycore.PyStringValue(json_response["product_id"])
    size = _pycore.PyDoubleValue(float(json_response["size"]))
    price = _pycore.PyDoubleValue(float(json_response["price"]))

    attributes = [
        maker_order_id,
        taker_order_id,
        time,
        trade_id,
        product_id,
        size,
        price,
    ]

    return attributes


rfq_stream_declaration = """CREATE STREAM S2 { \n
                        EVENT BUY { maker_order_id:string, taker_order_id:string, time:date, trade_id:int, product_id:string, \
                        size:float, price:float } \n,
                        EVENT SELL { maker_order_id:string, taker_order_id:string, time:date, trade_id:int, product_id:string, \
                        size:float, price:float } \n
                        }
                        """

## Options declaration
options = """CREATE QUARANTINE { \n
            FIXED_TIME 2 seconds {S} \n
            }"""

# ## Queries
# query_1 = """SELECT * FROM S\n
#                 WHERE (SELL as T1; BUY as T2; BUY as T3)\n
#                 FILTER T1[product_id = 'at-USD'] AND T2[product_id = 'BTC-USD'] AND T3[product_id = 'LTC-USD'] \n
#                 WITHIN 50 EVENTS"""
#
# query_2 = """SELECT * FROM S2\n
#                 WHERE (BUY as T1)\n
#                 FILTER T1[product_id = 'BTC-USD']\n
#                 WITHIN 100 EVENTS"""


async def websocket_listener(json_input, streamer):
    subscribe_message = json.dumps(json_input)

    message_count = 0
    start_time = time.time()

    event_dict = {"buy": 0, "sell": 1}
    stream_dict = {"ticker": 0, "match": 1}

    while True:
        try:
            async with websockets.connect(URI, ping_interval=None) as websocket:
                await websocket.send(subscribe_message)
                not_first_message = False
                while True:
                    response = await websocket.recv()
                    json_response = json.loads(response)
                    if not_first_message:
                        if json_response["type"] == "ticker":
                            attributes = create_ticker_attributes(json_response)
                            stream_id = stream_dict.get((json_response["type"]).lower())
                            event_type_id = event_dict.get(
                                (json_response["side"]).lower()
                            )
                            event = _pycore.PyEvent(event_type_id, attributes)
                            streamer.send_stream(stream_id, event)
                        elif json_response["type"] == "match":
                            attributes = create_matches_attributes(json_response)
                            stream_id = stream_dict.get((json_response["type"]).lower())
                            event_type_id = (
                                event_dict.get((json_response["side"]).lower()) + 2
                            )
                            event = _pycore.PyEvent(event_type_id, attributes)
                            print("Sending event")
                            streamer.send_stream(stream_id, event)

                    not_first_message = True

                    message_count += 1
                    elapsed_time = time.time() - start_time
                    if elapsed_time >= 1:
                        messages_per_second = message_count / elapsed_time
                        # print(f"Messages per second: {messages_per_second:.2f}")
                        message_count = 0
                        start_time = time.time()

        except (
            websockets.exceptions.ConnectionClosedError,
            websockets.exceptions.ConnectionClosedOK,
        ):
            print("Connection closed, retrying..")
            await asyncio.sleep(1)


# Opción de tener mas de una subscripción
async def main(streamer):
    tasks = [websocket_listener(ticker, streamer)]
    # tasks = [websocket_listener(rfq_matches, streamer)]
    # tasks.append(websocket_listener(rfq_matches, streamer))
    tasks.append(websocket_listener(matches, streamer))
    await asyncio.gather(*tasks)


def run_websocket():
    streamer_port = 5001
    streamer = _pycore.PyStreamer("tcp://localhost", streamer_port)

    # Comienza la conexión
    start_time_total = time.time()
    asyncio.run(main(streamer))


if __name__ == "__main__":
    start_time_total = time.time()
    try:
        # Aca van las configuraciones iniciales
        server_port = 5000

        client = _pycore.PyClient("tcp://localhost", server_port)

        stream_info = client.declare_stream(ticker_stream_declaration)

        print(f"Stream id: {stream_info.id}, Nombre: {stream_info.name}")
        for event in stream_info.events_info:
            print(event.name, event.id)

        second_stream_info = client.declare_stream(matches_stream_declaration)

        print(f"Stream id: {second_stream_info.id}, Nombre: {second_stream_info.name}")
        for event in second_stream_info.events_info:
            print(event.name, event.id)

        client.declare_option(options)

        # client.add_query(query_1)
        # client.add_query(query_2)

        # initial_port_number = 5003
        # final_port_number = 5005
        #
        # handlers = _pycore.subscribe_to_queries(
        #     client, initial_port_number, final_port_number
        # )

        # def my_handler(enumerator):
        #     for complex_event in enumerator:
        #         print(f"Data query: {complex_event.to_string()}")
        #
        # for i in range(len(handlers)):
        #     handlers[i].set_event_handler(my_handler)

        while True:
            try:
                run_websocket()

            except KeyboardInterrupt:
                print("Exiting WebSocket..")
                print(f"Total time: {time.time() - start_time_total}")
                break

            except Exception as e:
                print("Exited unexpectedly with error:", e)
                print("retrying in 5 seconds..")
                time.sleep(5)
                print(f"Total time: {time.time() - start_time_total}")

    except Exception as e:
        print("Exited unexpectedly with error when declaring with error:", e)
        print(f"Total time: {time.time() - start_time_total}")
