#pragma once

#include "shared/datatypes/value/value.hpp"
#include "shared/datatypes/value/attribute.hpp"
#include "shared/datatypes/value/boolean_literal.hpp"
#include "shared/datatypes/value/double_literal.hpp"
#include "shared/datatypes/value/integer_literal.hpp"
#include "shared/datatypes/value/long_literal.hpp"
#include "shared/datatypes/value/string_literal.hpp"
#include "shared/datatypes/value/undefined.hpp"
#include "shared/datatypes/value/operations/addition.hpp"
#include "shared/datatypes/value/operations/division.hpp"
#include "shared/datatypes/value/operations/modulo.hpp"
#include "shared/datatypes/value/operations/multiplication.hpp"
#include "shared/datatypes/value/operations/negation.hpp"
#include "shared/datatypes/value/operations/subtraction.hpp"
