[project]
name = "python-streamer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.7",
    "tqdm>=4.67.1",
    "websockets>=15.0.1",
]

[tool.uv]
package = false
