#!/bin/bash

    #################################################################
    # Auto-generated by scripts/generate_antlr.py                   #
    # DO NOT MODIFY DIRECTLY, modify it inside the python script.   #
    #################################################################

    RED='\033[0;31m'
    GREEN='\033[0;32m'
    NORMAL_OUTPUT='\033[0m'

    # Work at the scripts directory
    cd "$(dirname "$0")"

    export ANTLR_HOME="~/.local/bin"
    export ANTLR_JAR="$ANTLR_HOME/antlr-4.12.0-complete.jar"
    export CLASSPATH=".:$ANTLR_JAR:$CLASSPATH"
    alias antlr4="java -jar $ANTLR_JAR"
    alias grun="java org.antlr.v4.gui.TestRig"

    on_error() {
        echo -e "${RED}An error occurred, script has aborted.$NORMAL_OUTPUT"
    }

    set -e
    trap on_error ERR

    echo -e "${GREEN}Installing antlr-4.12.0" if it is not installed already.$NORMAL_OUTPUT
    mkdir -p ~/.local/bin
    cd ~/.local/bin && [ ! -f "antlr-4.12.0-complete.jar" ] && wget https://www.antlr.org/download/antlr-4.12.0-complete.jar
    cd -

    echo -e "${GREEN}Generating antlr files.$NORMAL_OUTPUT"

    if [ -d "autogenerated" ]; then
        rm -r "autogenerated"
    fi
    mkdir -p autogenerated
    java -jar ~/.local/bin/antlr-4.12.0-complete.jar -o autogenerated -no-listener -visitor -Dlanguage=Cpp StreamDeclarationLexer.g4
    java -jar ~/.local/bin/antlr-4.12.0-complete.jar -o autogenerated -no-listener -visitor -Dlanguage=Cpp StreamDeclarationParser.g4
    echo -e "${GREEN}Fishing the auto-generation of StreamDeclaration successfully.$NORMAL_OUTPUT"
    