cd "$(dirname "$0")"
cd ..
# Regenerate the antlr autogenerated files.
cd build/${BUILD_TYPE}
make grammar
cd ../../
conan build . -s build_type=${BUILD_TYPE} -s:h compiler=gcc \
              -s:h compiler.cppstd=gnu20 -s:h compiler.version=12.2\
              --build missing -vquiet
