#!/bin/bash

# Work at the root directory
cd "$(dirname "$0")"
cd ..

# Include common
source scripts/common.sh
_setArgs "$@"

# Regenerate the antlr autogenerated files.
cd build/${BUILD_TYPE}
ninja grammar
