#!/bin/bash
BUILD_TYPE="Release"
RED='\033[0;31m'
GREEN='\033[0;32m'
NORMAL_OUTPUT='\033[0m'

# Work at the root directory
# Should have conanfile.py present there.
cd "$(dirname "$0")"
cd ..

conan source .
conan install . -s build_type=${BUILD_TYPE} --build missing -vquiet

# Regenerate the antlr autogenerated files.
cd build/${BUILD_TYPE}
make grammar
cd ../../

conan build . -s build_type=${BUILD_TYPE} --build missing -vquiet
