import os
from os import path
import sys

def create_script(grammar_name, antlr4_version):
    script = f"""#!/bin/bash

    #################################################################
    # Auto-generated by scripts/generate_antlr.py                   #
    # DO NOT MODIFY DIRECTLY, modify it inside the python script.   #
    #################################################################

    RED='\\033[0;31m'
    GREEN='\\033[0;32m'
    NORMAL_OUTPUT='\\033[0m'

    # Work at the scripts directory
    cd "$(dirname "$0")"

    export ANTLR_HOME="~/.local/bin"
    export ANTLR_JAR="$ANTLR_HOME/antlr-VERSION-complete.jar"
    export CLASSPATH=".:$ANTLR_JAR:$CLASSPATH"
    alias antlr4="java -jar $ANTLR_JAR"
    alias grun="java org.antlr.v4.gui.TestRig"

    on_error() {{
        echo -e "${{RED}}An error occurred, script has aborted.$NORMAL_OUTPUT"
    }}

    set -e
    trap on_error ERR

    echo -e "${{GREEN}}Installing antlr-{antlr4_version}" if it is not installed already.$NORMAL_OUTPUT
    mkdir -p ~/.local/bin
    cd ~/.local/bin && [ ! -f "antlr-{antlr4_version}-complete.jar" ] && wget https://www.antlr.org/download/antlr-{antlr4_version}-complete.jar
    cd -

    echo -e "${{GREEN}}Generating antlr files.$NORMAL_OUTPUT"

    if [ -d "autogenerated" ]; then
        rm -r "autogenerated"
    fi
    mkdir -p autogenerated
    java -jar ~/.local/bin/antlr-VERSION-complete.jar -o autogenerated -no-listener -visitor -Dlanguage=Cpp {grammar_name}Lexer.g4
    java -jar ~/.local/bin/antlr-VERSION-complete.jar -o autogenerated -no-listener -visitor -Dlanguage=Cpp {grammar_name}Parser.g4
    echo -e "${{GREEN}}Fishing the auto-generation of {grammar_name} successfully.$NORMAL_OUTPUT"
    """
    return script.replace("VERSION", antlr4_version)


def create_antlr_autogeneration_scripts(antlr4_version):
    # Assuming we run this from the project root
    parsing_dir = path.join("src", "core_server", "internal", "parsing")
    script_name = "autogenerate_script.sh"
    
    directories = {
        "ceql_query": "CEQLQuery",
        "stream_declaration": "StreamDeclaration",
        "option_declaration": "OptionDeclaration"
    }

    for dir_name, grammar_name in directories.items():
        full_path = path.join(parsing_dir, dir_name, script_name)
        print(f"Generating {full_path}...")
        try:
            with open(full_path, "w", encoding="utf-8") as f:
                f.write(create_script(grammar_name, antlr4_version))
            os.chmod(full_path, 0o755) # Make executable
        except FileNotFoundError:
            print(f"Error: Directory {path.join(parsing_dir, dir_name)} not found. Make sure you are running from project root.")
            sys.exit(1)

if __name__ == "__main__":
    ANTLR4_VERSION = "4.12.0"
    create_antlr_autogeneration_scripts(ANTLR4_VERSION)
