#!/usr/bin/env python3
"""Generate ANTLR autogeneration scripts.

Extracted from conanfile.py - creates shell scripts that download the ANTLR jar
and generate parser/lexer files from .g4 grammars.
"""

import os
import stat

ANTLR4_VERSION = "4.12.0"

SCRIPT_TEMPLATE = r"""#!/bin/bash

#################################################################
# Auto-generated by generate_antlr.py                          #
# DO NOT MODIFY DIRECTLY, modify generate_antlr.py instead.    #
#################################################################

RED='\033[0;31m'
GREEN='\033[0;32m'
NORMAL_OUTPUT='\033[0m'

# Work at the scripts directory
cd "$(dirname "$0")"

export ANTLR_HOME="$HOME/.local/bin"
export ANTLR_JAR="$ANTLR_HOME/antlr-{version}-complete.jar"
export CLASSPATH=".:$ANTLR_JAR:$CLASSPATH"

on_error() {{
    echo -e "${{RED}}An error occurred, script has aborted.$NORMAL_OUTPUT"
}}

set -e
trap on_error ERR

echo -e "${{GREEN}}Installing antlr-{version} if it is not installed already.$NORMAL_OUTPUT"
mkdir -p "$ANTLR_HOME"
if [ ! -f "$ANTLR_JAR" ]; then
    wget -O "$ANTLR_JAR" https://www.antlr.org/download/antlr-{version}-complete.jar
fi

echo -e "${{GREEN}}Generating antlr files.$NORMAL_OUTPUT"

if [ -d "autogenerated" ]; then
    rm -r "autogenerated"
fi
mkdir -p autogenerated
java -jar "$ANTLR_JAR" -o autogenerated -no-listener -visitor -Dlanguage=Cpp {grammar}Lexer.g4
java -jar "$ANTLR_JAR" -o autogenerated -no-listener -visitor -Dlanguage=Cpp {grammar}Parser.g4
echo -e "${{GREEN}}Finishing the auto-generation of {grammar} successfully.$NORMAL_OUTPUT"
"""

GRAMMARS = {
    "ceql_query": "CEQLQuery",
    "stream_declaration": "StreamDeclaration",
    "option_declaration": "OptionDeclaration",
}

PARSING_DIR = os.path.join("src", "core_server", "internal", "parsing")


def main():
    for subdir, grammar_name in GRAMMARS.items():
        script_path = os.path.join(PARSING_DIR, subdir, "autogenerate_script.sh")
        content = SCRIPT_TEMPLATE.format(version=ANTLR4_VERSION, grammar=grammar_name)
        with open(script_path, "w", encoding="utf-8") as f:
            f.write(content)
        os.chmod(script_path, os.stat(script_path).st_mode | stat.S_IEXEC)
    print("ANTLR autogeneration scripts created successfully.")


if __name__ == "__main__":
    main()
